#!/bin/bash

make

if [ "$1" == "" ] ; then
  seed=`date +%s%N`
  text_seed=`./bin/timeToKey encode $seed`
else
  text_seed="$1"
fi

num_seed=`./bin/timeToKey decode $text_seed`
test_ly_name="test_$text_seed.ly"
solution_ly_name="solution_$text_seed.ly"
test_pdfName="exercise"
solution_pdfName="solution"
all_pdfName="exercise_solution"

notesPerLine=16
numberOfLines=13
numeroNote=$((notesPerLine*numberOfLines))

cat > $test_ly_name << @EOF
% Default layout:

\header {
  tagline = "Exercise n. $text_seed"
}

\layout {
  indent = #0
  line-width = #180 % #150
  #(layout-set-staff-size __STAFF_SIZE__)
}

\paper {
  bottom-margin = 1\cm
}

<<
  \new Staff \with { \omit TimeSignature } \new Voice = melody {
    \clef "treble"
    \hide KeySignature
    \hide Stem
    \time ${notesPerLine}/4
@EOF

cp $test_ly_name $solution_ly_name
sed -e "s/Exercise/Solution to exercise/g" -i $solution_ly_name

# Setting staff size
sed -e "s/__STAFF_SIZE__/26/g" -i $test_ly_name
sed -e "s/__STAFF_SIZE__/18/g" -i $solution_ly_name

cat >> $test_ly_name << @EOF
    \hide NoteHead
@EOF

# Exercise needs aways the same note, so we generate fake ones
bin/generaNote $numeroNote $num_seed 2 fake $notesPerLine >> $test_ly_name

# Solution here
bin/generaNote $numeroNote $num_seed 2 note $notesPerLine >> $solution_ly_name

testo=`bin/generaNote $numeroNote $num_seed 2 name 0`

cat >> $test_ly_name << @EOF
  }
  \new Lyrics \lyricsto melody {
  \override LyricText.font-name = #"Source Serif Pro"
%  \override LyricText.font-name = #"Equity Text A"
%  \override LyricText.font-name = #"Sunday Comics BB"
  \override LyricText.font-size = #-2 
$testo }
>>
@EOF

cat >> $solution_ly_name << @EOF
  }
>>
@EOF

lilypond -o "$test_pdfName" "$test_ly_name"
lilypond -o "$solution_pdfName" "$solution_ly_name"
rm -f "$test_ly_name" "$solution_ly_name"

which evince && evince "$test_pdfName.pdf" "$solution_pdfName.pdf" &
# pdftk "$test_pdfName.pdf" "$solution_pdfName.pdf" cat output "$all_pdfName.pdf"
# rm -f "$test_pdfName.pdf" "$solution_pdfName.pdf"
# evince "$all_pdfName.pdf"

