#!/bin/bash

make

if [ "$1" == "" ] ; then
  seed=`date +%s%N`
  text_seed=`./bin/timeToKey encode $seed`
else
  text_seed="$1"
fi

num_seed=`./bin/timeToKey decode $text_seed`
test_ly_name="test_$text_seed.ly"
solution_ly_name="solution_$text_seed.ly"
test_pdfName="exercise"
solution_pdfName="solution"
all_pdfName="exercise_solution"

numeroNote=360

cat > $test_ly_name << @EOF
% Default layout:

\header {
  tagline = "Exercise n. $text_seed"
}

\layout {
  indent = #0
  line-width = #180 % #150
  ragged-last = ##t
}

\paper {
  bottom-margin = 1\cm
}

<<
  \new Staff \with { \omit TimeSignature } \new Voice = melody {
    \hide KeySignature
    \hide Stem
@EOF

cp $test_ly_name $solution_ly_name
sed -e "s/Exercise/Solution to exercise/g" -i $solution_ly_name

cat >> $test_ly_name << @EOF
    \hide NoteHead
@EOF

# Only solutions
nota="d' "
for ((i=0; i<numeroNote; i=i+1)); do
  echo -n "$nota" >> $test_ly_name
  nota="d' "
  if ((i % 4 == 0)); then
          echo "" >> $test_ly_name
  fi
done
echo "" >> $test_ly_name

# Only exercize
bin/generaNote $numeroNote $num_seed 2 note >> $solution_ly_name

testo=`bin/generaNote $numeroNote $num_seed 2 name`

cat >> $test_ly_name << @EOF
  }
  \new Lyrics \lyricsto melody {
  \override LyricText.font-name = #"Source Serif Pro"
%  \override LyricText.font-name = #"Equity Text A"
%  \override LyricText.font-name = #"Sunday Comics BB"
  \override LyricText.font-size = #-2 
$testo }
>>
@EOF

cat >> $solution_ly_name << @EOF
  }
  \new Lyrics \lyricsto melody {
  \override LyricText.font-name = #"Source Serif Pro"
%  \override LyricText.font-name = #"Equity Text A"
%  \override LyricText.font-name = #"Sunday Comics BB"
  \override LyricText.font-size = #-2
$testo }
>>
@EOF

lilypond -o "$test_pdfName" "$test_ly_name"
lilypond -o "$solution_pdfName" "$solution_ly_name"
rm -f "$test_ly_name" "$solution_ly_name"

which evince && evince "$test_pdfName.pdf" "$solution_pdfName.pdf" &
# pdftk "$test_pdfName.pdf" "$solution_pdfName.pdf" cat output "$all_pdfName.pdf"
# rm -f "$test_pdfName.pdf" "$solution_pdfName.pdf"
# evince "$all_pdfName.pdf"

